export default {
  FROALA_API_KEY: process.env.REACT_APP_FROALA_API_KEY,
  API_ENDPOINT: process.env.REACT_APP_API_ENDPOINT,
  TOKEN_KEY: process.env.REACT_APP_TOKEN_KEY,
  AWS_ACCESS_KEY: process.env.REACT_APP_ACCESS_KEY
};
